### ISSUE TITLE
Tabulate testing strategies for clarity

### ISSUE THREAD

**Issue by jonahdf** [jonahdf/COVID-Event-Safety-Modeling#10]
> These should be tabulated further up; it's not immediately obvious at a glance that four separate strategies are being tested as currently written up top

**Comment by jonahdf** [comment]
Added a table. @JoviaNierenberg can look over, and potentially move to methods section if necessary

**Comment by JoviaNierenberg** [comment]
Added summary sentence to the results: "We simulated four testing strategies: entry antigen testing, daily antigen testing, PCR test 2 days prior to the event, and PCR test 4 days prior to the event."

Moved interventions table to the methods. Separated population characteristics and mitigation measures into multiple tables, to make it clearer which numbers will be used for which models.
