### ISSUE TITLE
Prevalence - Introduction

### ISSUE THREAD

**Issue by JoviaNierenberg** [jonahdf/COVID-Event-Safety-Modeling#8]
We definitely need to explain how this is being measured, given the fact that our surveillance for prevalence at the county- or state-level still leaves a lot to be desired (i.e., it's difficult to know what the prevalence is if everyone in the population isn't being regularly tested)

At the very least, I might recommend something like test positivity rate in addition to this (though this metric also has issues given that different localities have different standards for who does or doesn't get tested, which makes this concept difficult to generalize)

**Comment by JoviaNierenberg** [comment]
Briefly describe in introduction

**Comment by jonahdf** [comment]
[IHME](https://covid19.healthdata.org/united-states-of-america) has long-range forecasts that can be used to calibrate prevalence. 

We can also use a default case ascertainment ratio to calculate prevalence, or use test positivity + cases to calculate it ourselves.

**Comment by JoviaNierenberg** [comment]
Moved comment to Methods prevalence issue, closing this Introduction prevalence issue.
